use_frameworks!

target 'ZKCategories_Example' do
  pod 'ZKCategories', :path => '../', :subspecs => ['ZKKVOSAFE']

  target 'ZKCategories_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
