use_frameworks!

target 'ZKCategories_Example' do
  pod 'ZKCategories', :subspecs => ['ZKKVOSAFE'], :path => '../'

  target 'ZKCategories_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
